# consul服务端口号
server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  # consul注册中心的地址
  cloud:
    consul:
      host: 192.168.52.131
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

